npm add babel-cli
npm add babel-core
npm add babel-loader
npm add babel-plugin-transform-class-properties
npm add babel-plugin-transform-object-rest-spread
npm add babel-polyfill
npm add babel-preset-env
npm add babel-preset-react
npm add css-loader
npm add emailjs-com
npm add express
#npm add extract-text-webpack-plugin
npm add firebase
npm add history
npm add moment
npm add namor
npm add node-rest-client
npm add node-sass
npm add normalize.css
npm add numeral
npm add react
npm add react-addons-shallow-compare
npm add react-copy-to-clipboard
#npm add react-dates
npm add react-dom
npm add react-modal
npm add react-redux
npm add react-router-dom
npm add react-select
npm add react-table
npm add react-tooltip
npm add redux
npm add redux-mock-store
npm add redux-thunk
npm add sass-loader
npm add style-loader
npm add uuid
npm add validator
npm add webpack

npm add cross-env
npm add dotenv
npm add enzyme
npm add enzyme-to-json
npm add jest
npm add react-test-renderer
npm add webpack-dev-server

